name: sexism
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11.0
  - pytorch
  - jupyter
  - chardet
  - pip
  - pip:
      - simpletransformers==0.70.0
      - transformers==4.38.2
      - numpy
      - scikit-learn
